### ISSUE TITLE
can we use JS because all the function signature is removed by tsc

### ISSUE THREAD

**Issue by legend80s** [FliPPeDround/console-next#1]
![image](https://user-images.githubusercontent.com/8603442/164911009-092ebd8b-4c0d-4297-9a59-26809b638331.png)

It is an excellent repo, thanks for your effort. But the mysterious params is not user friendly. It force me to check the source code or your document for usage.

**Comment by FliPPeDround** [comment]
终于有时间来搞一下这个了，这个问题是由压缩代码的插件引起的，并不是ts。如果你在vscode这类编辑器中使用的话，因为有d.ts文件将会获得良好的代码类型提示。我切换了压缩工具解决这个问题，但es文件增加了2kb  :( ，再次感谢你对这个项目的支持🙏
